#
# travis-ci definition file
# below matrix points to docker images
#
sudo: false
dist: trusty

env:
  matrix:
  - CENTOS=centos:7.5.1804 KERNEL=3.10.0-862 BUILD=7.5.1804
  - CENTOS=centos:7.4.1708 KERNEL=3.10.0-693.21.1 BUILD=7.4.1708
  - CENTOS=centos:7.4.1708 KERNEL=3.10.0-693 BUILD=7.4.1708
  - CENTOS=centos:7.3.1611 KERNEL=3.10.0-514 BUILD=7.3.1611
  - CENTOS=centos:7.2.1511 KERNEL=3.10.0-327 BUILD=7.2.1511
  - CENTOS=centos:7.1.1503 KERNEL=3.10.0-229 BUILD=7.1.1503
  - CENTOS=centos:7.0.1406 KERNEL=3.10.0-123 BUILD=7.0.1406
  - CENTOS=centos:6.9 KERNEL=2.6.32-696 BUILD=6.9
  - CENTOS=centos:6.8 KERNEL=2.6.32-642 BUILD=6.8
  - CENTOS=centos:6.7 KERNEL=2.6.32-573 BUILD=6.7
  - CENTOS=centos:6.6 KERNEL=2.6.32-504 BUILD=6.6

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce
  - sudo docker --version
  - sudo docker pull $CENTOS

script:
  - bash setup_travis_env.sh
